export default{
    path:"/dingdan",
    name:"dingdan",
    component:()=>import("@pages/mine/dingdan"),
    children:[
        {
            path:"/dingdan",
            redirect:"/dingdan/all"
        },
        {
            path:"all",
            name:"all",
            component:()=>import("@lib/dindan/all")
        },
        {
            path:"daifu",
            name:"daifu",
            component:()=>import("@lib/dindan/daifu")
        },
        {
            path:"daifahuo",
            name:"daifahuo",
            component:()=>import("@lib/dindan/daifahuo")
        },
        {
            path:"daishouhuo",
            name:"daishouhuo",
            component:()=>import("@lib/dindan/daishouhuo")
        }
    ]
}
